// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOWRS5hc5XN-5sTb3oBuCyiuV5jQeurjw',
    appId: '1:273247794856:web:93157629f993917589749d',
    messagingSenderId: '273247794856',
    projectId: 'mawqifi-81e4b',
    authDomain: 'mawqifi-81e4b.firebaseapp.com',
    databaseURL: 'https://mawqifi-81e4b-default-rtdb.firebaseio.com',
    storageBucket: 'mawqifi-81e4b.firebasestorage.app',
    measurementId: 'G-R5N4NSED7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ8utxrbBXFkij93R0qaObWlN2GSkId68',
    appId: '1:273247794856:android:8d70ce9c33eaaa1889749d',
    messagingSenderId: '273247794856',
    projectId: 'mawqifi-81e4b',
    databaseURL: 'https://mawqifi-81e4b-default-rtdb.firebaseio.com',
    storageBucket: 'mawqifi-81e4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAnJzzvRb9owBDgEUxqJ5mIOtstPmu3qs',
    appId: '1:273247794856:ios:f54ae66890ec779b89749d',
    messagingSenderId: '273247794856',
    projectId: 'mawqifi-81e4b',
    databaseURL: 'https://mawqifi-81e4b-default-rtdb.firebaseio.com',
    storageBucket: 'mawqifi-81e4b.firebasestorage.app',
    iosBundleId: 'com.smartparkingble.smartParkingBle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAnJzzvRb9owBDgEUxqJ5mIOtstPmu3qs',
    appId: '1:273247794856:ios:f54ae66890ec779b89749d',
    messagingSenderId: '273247794856',
    projectId: 'mawqifi-81e4b',
    databaseURL: 'https://mawqifi-81e4b-default-rtdb.firebaseio.com',
    storageBucket: 'mawqifi-81e4b.firebasestorage.app',
    iosBundleId: 'com.smartparkingble.smartParkingBle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOWRS5hc5XN-5sTb3oBuCyiuV5jQeurjw',
    appId: '1:273247794856:web:3af1068cb2c01aaa89749d',
    messagingSenderId: '273247794856',
    projectId: 'mawqifi-81e4b',
    authDomain: 'mawqifi-81e4b.firebaseapp.com',
    databaseURL: 'https://mawqifi-81e4b-default-rtdb.firebaseio.com',
    storageBucket: 'mawqifi-81e4b.firebasestorage.app',
    measurementId: 'G-72Q06BYGZF',
  );
}
